# Generated by Django 3.2.4 on 2021-07-20 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaint', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='phonenumber',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
