# Generated by Django 3.2.4 on 2021-07-20 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('phonenumber', models.AutoField(max_length=10, primary_key=True, serialize=False)),
                ('subject', models.CharField(max_length=50)),
                ('description', models.TextField()),
            ],
        ),
    ]
